### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_url#1]
Rex frisch von Redaxo.org
```

"rex_functional_exception" thrown in /Applications/MAMP/htdocs/rex5basic/redaxo/src/addons/url/lib/Url/Url.php on line 693
Please install a rewriter addon and call Url::setRewriter(Rewriter $rewriter).

#0 /Applications/MAMP/htdocs/rex5basic/redaxo/src/addons/url/boot.php(18): Url\Url::boot()
#1 /Applications/MAMP/htdocs/rex5basic/redaxo/src/core/lib/packages/package.php(226): include('/Applications/M...')
#2 /Applications/MAMP/htdocs/rex5basic/redaxo/src/core/packages.php(55): rex_package->includeFile('boot.php')
#3 /Applications/MAMP/htdocs/rex5basic/redaxo/src/core/backend.php(105): include_once('/Applications/M...')
#4 /Applications/MAMP/htdocs/rex5basic/redaxo/src/core/boot.php(105): require('/Applications/M...')
#5 /Applications/MAMP/htdocs/rex5basic/redaxo/index.php(9): require('/Applications/M...')
#6 {main}

```

Kommt sofern yrewrite noch nicht installiert ist..

**Comment by tbaddade** [comment]
Wurde mit diesem Commit behoben.
https://github.com/tbaddade/redaxo_url/commit/3666f50e18aba604e6fc7cc2518517f101975d89

Die Fehlermeldung erscheint jetzt unter Packages
